package org.t0tec.tutorials.helloworld;
// Generated Dec 17, 2014 4:25:45 PM by Hibernate Tools 3.2.0.beta8


import java.util.HashSet;
import java.util.Set;

/**
 * Messages generated by hbm2java
 */
public class Messages  implements java.io.Serializable {

    // Fields    

     private long messageId;
     private Messages messages;
     private String messageText;
     private Set messageses = new HashSet(0);

     // Constructors

    /** default constructor */
    public Messages() {
    }

	/** minimal constructor */
    public Messages(long messageId) {
        this.messageId = messageId;
    }
    /** full constructor */
    public Messages(long messageId, Messages messages, String messageText, Set messageses) {
       this.messageId = messageId;
       this.messages = messages;
       this.messageText = messageText;
       this.messageses = messageses;
    }
   
    // Property accessors
    public long getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(long messageId) {
        this.messageId = messageId;
    }
    public Messages getMessages() {
        return this.messages;
    }
    
    public void setMessages(Messages messages) {
        this.messages = messages;
    }
    public String getMessageText() {
        return this.messageText;
    }
    
    public void setMessageText(String messageText) {
        this.messageText = messageText;
    }
    public Set getMessageses() {
        return this.messageses;
    }
    
    public void setMessageses(Set messageses) {
        this.messageses = messageses;
    }




}


